import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import styles from "./columns.module.scss";
import Share from "../../components/Share";
import SeeToo from "@/src/components/SeeToo";
import DigitalWeekly from "@/src/components/DigitalWeekly";
import DigitalBiWeekly from "@/src/components/digitalBiWeekly";

export default function Colunas(){
    const { query } = useRouter();

    const [dados, setDados] = useState([]);
    const [load, setLoad] = useState(false);
    
    useEffect(() =>{   
            const colunaTitulo = query?.coluna;
            fetch('/api/controller/buscarBancoUnico/',{
                method: 'POST',
                body: JSON.stringify({'busca': 'colunistas', 'indicadorBusca': colunaTitulo }), 
                headers:{
                    'Content-Type': 'application/json'
                }
            }).then(response => response.json()).then(data => {
                setDados(data);
                setLoad(true);
            });
    }, [query?.coluna]);
    
    if(load)
    return(
        <>
            <Head>
                <title> Colunas - JS </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <main>
                <div className={styles.headerNoticiasIndi}>
                    <h1 className="text-2xl py-2"> { dados.titulo }</h1>
                    <h4> Por <a className="underline" href={`/columns/colunista/${dados.nome}`}> { dados.nome }</a></h4>
                    <h4>Publicado em { dados.data }</h4> 
                </div>
                <div className={styles.conteudoNoticiasIndi}>
                    <Share/>
                    <p className="text-justify">
                        { dados.texto }
                    </p>
                </div>
                <SeeToo/>
                <DigitalWeekly/>
                <DigitalBiWeekly/>
            </main>
        </>
    );
}