import  Head  from "next/head";
import { useEffect, useState } from "react";
import  LegalPublicationsForm  from "../../components/legalPublicationsForm";
import SeeToo from "../../components/SeeToo";
import DigitalWeekly from "@/src/components/DigitalWeekly";
import DigitalBiWeekly from "@/src/components/digitalBiWeekly";

export default function LegalPublications() {
    const [dadosPrefeituras, setDadosPrefeituras] = useState([]);
    const [dadosCamaras, setDadosCamaras] = useState([]);
    const [dadosSindicatos, setDadosSindicatos] = useState([]);
    const [selecaoPre, setSelecaoPre] = useState("Prefeitura");
    const [selecaoCam, setSelecaoCam] = useState("Camara");
    const [selecaoSin, setSelecaoSin] = useState("Sindicato");

    const [load, setLoad] = useState(false);

    useEffect(() =>{

        fetch('api/controller/buscarBanco/',{
            method: 'POST',
            body: JSON.stringify({'busca': 'prefeituras'}), 
            headers:{
                'Content-Type': 'application/json'
            }
        }).then(response => response.json()).then(data => {
            
            let teste = new Array();
            data.map((dado : any) =>(
                teste.push(dado.cidade)
            ));
            let teste2 = [... new Set(teste)];

            setDadosPrefeituras( teste2 );

        });

        fetch('api/controller/buscarBanco/',{
            method: 'POST',
            body: JSON.stringify({'busca': 'camaras'}), 
            headers:{
                'Content-Type': 'application/json'
            }
        }).then(response => response.json()).then(data => {
            // setDadosCamaras( data.reverse() );
            let teste = new Array();
            data.map((dado : any) =>(
                teste.push(dado.cidade)
            ));
            let teste2 = [... new Set(teste)];

            setDadosCamaras( teste2 );

        });

        fetch('api/controller/buscarBanco/',{
            method: 'POST',
            body: JSON.stringify({'busca': 'sindicatos'}), 
            headers:{
                'Content-Type': 'application/json'
            }
        }).then(response => response.json()).then(data => {
            let teste = new Array();
            data.map((dado : any) =>(
                teste.push(dado.cidade)
            ));
            let teste2 = [... new Set(teste)];

            setDadosSindicatos( teste2 );
            //setDadosSindicatos( data.reverse() );
            setLoad(true);
            
        });

    }, []);

    function cidadeSindicato(e : any){
        e.preventDefault();
        setSelecaoSin(e.target.value)
        if(e.target.value != ""){
            window.location.assign(`/legalPublications/sindicatos/${e.target.value}`);
        }
        
    }

    function cidadePrefeitura(e: any){
        e.preventDefault();
        setSelecaoPre(e.target.value)
        if(e.target.value != ""){
            window.location.assign(`/legalPublications/prefeituras/${e.target.value}`);
        }
    }

    
    function cidadeCamara(e: any){
        e.preventDefault();
        setSelecaoCam(e.target.value)
        if(e.target.value != ""){
            window.location.assign(`/legalPublications/camaras/${e.target.value}`);
        }
    }

    if(load){
        return (
            <>
                <Head>
                    <title> Publicações Legais - JS </title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.png" />
                </Head>
                <main className="w-full  items-center justify-center">
                    <div className="flex flex-col text-center p-8">
                        <h1 className="font-light text-2xl uppercase"> Publicações Legais </h1>
                        <h2 className="font-light text-xl pt-4"> Veja os principais Editais da nossa região! </h2>
                    </div>

                    <section className="flex items-center justify-between m-auto w-4/5">
                        
                        <select 
                            name="prefeituras" 
                            value={selecaoPre} 
                            onChange={(e) => cidadePrefeitura(e)}
                            className="p-4 bg-green-300 items-center text-center font-semibold uppercase w-36 rounded-lg"
                        >
                            <option value="" >
                                Prefeituras
                            </option>
                            {
                                dadosPrefeituras.map((prefeitura, key) => (
                                    <option value={prefeitura} key={key}> {prefeitura}</option>
                                ))
                            }

                        </select>

                        <select name="camaras" value={selecaoCam} onChange={(e) => cidadeCamara(e)} 
                            className="p-4 ml-20 bg-green-300 items-center text-center font-semibold uppercase w-36 rounded-lg">
                            <option value="">Câmaras</option>
                            {
                                dadosCamaras.map((camaras, key) => (
                                    <option value={camaras} key={key}> {camaras}</option>
                                ))
                            }

                        </select>

                        <select name="sindicato" value={selecaoSin} onChange={(e) => cidadeSindicato(e)} 
                        className="p-4 bg-green-300 items-center text-center  font-semibold uppercase w-60 rounded-lg">

                            <option value="">Sindicatos e Entidades</option>
                            {
                                dadosSindicatos.map((sindicato, key) => (
                                    <option value={sindicato} key={key}> {sindicato}</option>
                                ))
                            }

                        </select>

                    </section>
                    <section>
                        <LegalPublicationsForm />
                    </section>
                    <section>
                        <SeeToo />
                        <DigitalWeekly />
                        <DigitalBiWeekly/>
                    </section>
                    
                </main>
            </>
        );
    }
}