import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import LegalPublicationsForm from "../../../components/legalPublicationsForm";
import DigitalWeekly from "@/src/components/DigitalWeekly";
import SeeToo from "@/src/components/SeeToo";
import styles from "../legalPubli.module.scss";
import DigitalBiWeekly from "@/src/components/digitalBiWeekly";

export default function News(){
    const { query } = useRouter();

    const [dadosCamaras, setDadosCamaras] = useState([]);
    const [selecaoCam, setSelecaoCam] = useState("Camara");

    const [dados, setDados] = useState([]);
    const [load, setLoad] = useState(false);

    useEffect(() =>{   
            const url = query?.camara;

            fetch('/api/controller/buscarBanco/',{
                method: 'POST',
                body: JSON.stringify({'busca': 'camaras'}), 
                headers:{
                    'Content-Type': 'application/json'
                }
            }).then(response => response.json()).then(data => {
                
                let teste = new Array();
                data.map((dado : any) =>(
                    teste.push(dado.cidade)
                ));
                let teste2 = [... new Set(teste)];
                
                setDadosCamaras( teste2 );
    
            });

            fetch('/api/controller/buscarBancoUnico/',{
                method: 'POST',
                body: JSON.stringify({'busca': 'camaras', 'indicadorBusca': url }), 
                headers:{
                    'Content-Type': 'application/json'
                }
            }).then(response => response.json()).then(data => {
                setDados(data);
                setLoad(true);
            });
    }, [query?.camara]);
    
    function cidadeCamara(e: any){
        e.preventDefault();
        setSelecaoCam(e.target.value)
        if(e.target.value != ""){
            window.location.assign(`/legalPublications/camaras/${e.target.value}`);
        }
    }

    if(load){
        return(
            <>
                <Head>
                    <title> Publicações Legais - JS </title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.png" />
                </Head>
                <main>
                    <div className="flex flex-col text-center p-8">
                        <h1 className="font-light text-2xl uppercase"> Publicações Legais </h1>
                        <h2  className="font-light text-xl pt-4"> Veja os principais Editais da nossa região! </h2>
                    </div>
                    <div className="flex items-center justify-between py-8 w-4/5 m-auto">
                        <select name="prefeituras" className="p-4 bg-green-300 items-center text-center  font-semibold uppercase w-36 rounded-lg">
                            <option value="">Prefeituras</option>
                        </select>

                        <select name="camaras" value={selecaoCam} onChange={(e) => cidadeCamara(e)} className="p-4 ml-20 bg-green-300 items-center text-center  font-semibold uppercase w-36 rounded-lg">
                            <option value="">Câmaras</option>
                            {
                                dadosCamaras.map((camaras,key) => (
                                    <option value={camaras} key={key}> { camaras}</option>
                                ))
                            }   

                        </select>

                        <select name="sindicato" className="p-4 bg-green-300 items-center text-center  font-semibold uppercase w-60 rounded-lg">
                            <option value="">Sindicatos e Entidades</option>
                        </select>
                    </div>
                    <div className={styles.componentesCards}>
                        <h1>Câmara de {query?.camara}</h1>
                        {
                            dados.map((dado,key) => (
                                <a href={`/legalPublications/camaras/camaraBusca/${dado.titulo}`} target="_blank" className={styles.cardLegalPublication}>
                                    <div className={styles.cardConteudo}>
                                        <img src={`data:image;base64, ${Buffer.from(dado.imagem.data).toString('base64')}`} alt="" />
                                        <div className={styles.cardConteudoDentro}>
                                            <h2>Câmara {dado.cidade} - {dado.titulo}</h2>

                                            <h3>Por Câmara {dado.cidade}</h3>
                                        </div>
                                    </div>
                                </a>
                            ))
                        }
                    </div>
                    <SeeToo/>
                    <DigitalWeekly/>
                    <DigitalBiWeekly/>
                </main>
            </>
        );}
    else{
        return(
            <>
                <Head>
                        <title>Jornal Sudoeste </title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <link rel="icon" href="/favicon.png" />
                </Head>
            </>
        );
    }
}