import Head from "next/head";
import Image from "next/image";

import jornalRetrato from '../../assets/imageojornal1.jpeg';
import jornalPaisagem from '../../assets/imageojornal2.jpeg';
import { Advertising } from "@/src/components/Advertising";
import DigitalWeekly from "@/src/components/DigitalWeekly";
import DigitalBiWeekly from "@/src/components/digitalBiWeekly";

export default function Journal() {
    return (
        <>
            <Head>
                <title>O Jornal - JS</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>

            <main className="w-full flex flex-col items-center justify-center">

                <div className="flex flex-col text-center p-8 ">
                    <h1 className="font-light text-2xl uppercase"> O Jornal</h1>
                    <h2 className="font-light text-xl pt-4"> Saiba mais sobre o Jornal do Sudoeste </h2>
                </div>

                <div className="m-w-full items-center p-8 w-4/5 m-auto">
                    <Image
                        src={jornalRetrato}
                        alt=""
                        width={350}

                        className="float-right mx-4 border rounded"
                    />
                    <p className="text-justify lg:text-lg text-sm">
                        Jornal do Sudoeste foi lançado em março de 1998, em Brumado, com a
                        proposta de adotar uma linha editorial crítica e independente, abrindo
                        espaço para todas as correntes de pensamento e pautando sua atuação na
                        busca intransigente da verdade. Graças a essa postura o JS consolidou-se
                        com um dos mais respeitados veículos de comunicação social das regiões
                        Sudoeste, Oeste e Chada Diamantina da Bahia.
                        <br />
                        Desde seu lançamento, o JS vem revolucionando a imprensa regional. Foi
                        pioneiro na adoção de cores nas edições impressas, em todas as suas
                        páginas, e no lançamento de Suplementos Especiais que extrapolam o
                        simples apelo comercial, envolvendo a comunidade em reflexões sobre
                        temas de interesse geral por ocasião do Natal e dos aniversários de
                        emancipação de municípios da sua área de abrangência de circulação.
                        <br />
                        Ao comemorar seu oitavo ano de fundação, em 2007, as edições impressas
                        do JS, que já circulava em mais de noventa municípios das regiões Sudoeste,
                        Oeste e Chapada Diamantina da Bahia, passou a circular com regularidade
                        em Salvador, sendo distribuído na Governadoria e em órgãos da estrutura do
                        Governo do Estado e na Assembleia Legislativa da Bahia e Agências de
                        Publicidade, além de chegar a assinantes em diversos municípios da
                        Federação (Distrito Federal, Goiás, Minas Gerais, São Paulo, Santa Catarina,
                        entre outros).<br />
                        Ao completar 17 anos, em março de 2015, o JS passou por uma profunda
                        reformulação editorial, gráfica e de marca. Tanto no papel quanto no online,
                        em tablets e nos celulares as mudanças deram início a um ciclo de
                        reposicionamento e transformação.<br />
                        Pouco mais de um ano depois, movido pelo mesmo espírito de ousadia e
                        inovação, como tem sido desde sua fundação em março de 1998, o JS
                        inaugurou um novo ciclo no jornalismo regional, apresentando aos seus
                        assinantes e leitores o que há de mais moderno e avançado na apresentação
                        visual de um jornal e um Portal de Notícias digital na região, com versão
                        moderna, ganhou melhor organização da informação e da navegação,
                        permitindo que conteúdos jornalísticos e espaços publicitários ganhem mais
                        destaque, além de foco em vídeos
                        <br />
                    </p>

                </div>

                <Advertising />

                <div className="m-w-full items-center md:justify-center p-8 w-4/5 m-auto">
                    <Image src={jornalPaisagem}
                        alt=""
                        width={500}
                        className="lg:float-left m-4 border rounded"
                    />
                    <p className="text-justify lg:text-lg text-sm ">
                        Em março de 2020, por conta das medidas restritivas impostas para combate
                        da Pandemia da Covid-19, o JS teve que se adaptar rapidamente às novas
                        demandas do seu público leitor e à nova realidade do mercado. A migração
                        do impresso para o digital foi uma das principais medidas tomadas para
                        manter a relevância e a proximidade com seu público – que passou a
                        consumir mais informações online - e buscar ampliar o alcance da publicação.
                        Essa transição, no entanto, não implicou na perda a essência do jornalismo,
                        pelo contrário, os princípios éticos que regem o bom jornalismo continuaram
                        sendo intransigentemente seguidos, assegurando a qualidade e a
                        credibilidade das informações veiculadas. A veracidade, a imparcialidade, a
                        contextualização e a pluralidade das fontes, além do enfrentamento firme à
                        desinformação e às fake news continuam sendo prioridades na produção e
                        reprodução de conteúdo, mesmo em meio a um cenário de incertezas e
                        desafios sem precedentes.<br />
                        Com a adaptação para o meio digital, o JS tem buscado uma maior interação
                        com o público e, nesse contexto, numa iniciativa pioneira no jornalismo
                        regional, estreou um novo produto, o JS Noticias, editado às segundas,
                        terças e sextas-feiras, com destaque para as principais notícias regionais, do
                        Estado, nacionais e de interesse público nas diversas áreas – Saúde, Educação,
                        Comportamento e Entretenimento, ampliando, dessa forma, a oferta de
                        matérias jornalísticas, com o mesmo padrão de qualidade e compromisso
                        com a verdade dos fatos.<br />
                        E, depois de uma reformulação e modernização de sua identidade visual, aos
                        26 anos, baseado no tripé tecnologia, inovação e interatividade a serviço da
                        informação, o JS estreia um novo Portal de Notícias, com formato mais leve
                        e layout mais limpo, com objetivo de oferecer uma navegação mais rápida e
                        descomplicada, aumentar o time spent e trabalhar tendências das redes
                        sociais, que ganha um Departamento - Estratégia Digital/Edição De
                        Imagens/Media Digita - dentro da Redação já visando novos projetos –
                        podcasts, lives e vídeos – que se vão se tornar ferramentas para manter a
                        conexão com os leitores e proporcionar uma experiência mais imersiva e
                        participativa.<br />
                        Dessa forma, apesar das mudanças provocadas pela pandemia, o JS
                        conseguiu se reinventar, preservando sua missão de informar, educar,
                        entreter, sempre pautado pelos princípios éticos e pela busca intransigente
                        da verdade. A resiliência e a criatividade demonstradas nesse novo tempo
                        reforçam a importância e a relevância do jornalismo em momentos de crise,
                        enfatizando seu papel como pilar fundamental da democracia e da
                        sociedade

                    </p>
                </div>
            </main>
            <DigitalWeekly />
            <DigitalBiWeekly/>
        </>
    )
}