import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import styles from "../jornalDigital.module.scss";
import Share from "../../components/Share";
import { Advertising } from "@/src/components/Advertising";
import SeeToo from "@/src/components/SeeToo";
import DigitalWeekly from "@/src/components/DigitalWeekly";
import { Buffer } from 'buffer';  // Importando Buffer

export default function News() {
    const { query } = useRouter();

    const [dados, setDados] = useState([]);
    const [load, setLoad] = useState(false);
    const [error, setError] = useState(null);

    useEffect(() => {
        const digitalTitulo = query?.digital;
        if (digitalTitulo) {
            fetch('/api/controller/buscarBanco/', {
                method: 'POST',
                body: JSON.stringify({ 'busca': digitalTitulo }),
                headers: {
                    'Content-Type': 'application/json'
                }
            })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.json();
                })
                .then(data => {
                    setDados(data);
                    setLoad(true);
                })
                .catch(error => {
                    setError(error.message);
                    setLoad(true);
                });
        }
    }, [query?.digital]);

    if (!load) {
        return (
            <>
                <Head>
                    <title>Jornal Sudoeste</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.png" />
                </Head>
                <main>
                    <div>Loading...</div>
                </main>
            </>
        );
    }

    if (error) {
        return (
            <>
                <Head>
                    <title>Jornal Sudoeste</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.png" />
                </Head>
                <main>
                    <div>Error: {error}</div>
                </main>
            </>
        );
    }

    let header;
    switch (query?.digital) {
        case "edicoes_diarias":
            header = "Edições Diárias";
            break;
        case "edicoes_semanais":
            header = "Edições Semanais";
            break;
        case "edicoes_quinzenais":
            header = "Edições Quinzenais";
            break;
        default:
            header = "Edições";
            break;
    }

    return (
        <>
            <Head>
                <title>Jornal do Sudoeste</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <main>
                <div className={styles.mainPageNoticias}>
                    <h2>{header}</h2>
                    <div className="w-full min-h-[300px] flex flex-wrap">
                        {dados.map((digital, key) => (
                            <div key={key} className={styles.noticiasCardMenor}>
                                <a href={`/digitalWeekly/${digital.titulo}`}>
                                    <img
                                        src={`data:image;base64, ${Buffer.from(digital.imagem.data).toString('base64')}`}
                                        alt={digital.titulo}
                                        className=""
                                    />
                                    <div className={styles.cardDentro}>
                                        <h3>{digital.titulo}</h3>
                                    </div>
                                </a>
                            </div>
                        ))}
                    </div>
                </div>
            </main>
        </>
    );
}
