import { Advertising } from "@/src/components/Advertising";
import DigitalWeekly from "@/src/components/DigitalWeekly";
import Head from "next/head";
import Image from "next/image";
import DigitalBiWeekly from "@/src/components/digitalBiWeekly";

export default function TermosdeUso() {
    return (
        <>
            <Head>
                <title>O Jornal - Termos de Uso</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>

            <main className="w-full flex flex-col items-center justify-center">

                <div className="flex flex-col text-center p-8">
                    <h1 className="font-light text-2xl uppercase"> Aviso de Direitos Autorais e de Propriedade Intelectual</h1>
                    {/* <h2 className="font-light text-xl pt-4"> Saiba mais sobre o Jornal do Sudoeste </h2> */}
                </div>

                <div className="m-w-full items-center p-8 w-4/5 m-auto">

                    <p className="text-justify lg:text-lg text-sm">

                        
                        Como veículo de comunicação, o Jornal e Portal de Notícias do Jornal do Sudoeste respeita e
                        valoriza os direitos autorais de todas os conteúdos e materiais – textos, fotografias, ilustrações,
                        vídeos etc) editados no Jornal do Sudoeste, JS Notícias e/ou reproduzidos no Portal
                        https://jornaldosudoeste.com são protegidos por Direitos Autorais e/ou Direitos de
                        Propriedade Intelectual e, portanto, pertencem, aos seus respectivos criadores ou detentores
                        de direitos, sendo expressamente proibida a reprodução, distribuição, exibição, edição ou
                        qualquer outro uso não autorizado dos conteúdos sem a devida autorização prévia do Jornal
                        do Sudoeste e/ou dos detentores dos Direitos Autorais e Direitos de Propriedade Intelectual.
                        Os infratores estarão sujeitos às penalidades previstas na legislação vigente. Caso deseje utilizar
                        algum conteúdo do Jornal e Portal de Notícias do Jornal do Sudoeste, entre em contato
                        conosco para obter a devida autorização.<br /> <br /> 
                        Agradecemos pela compreensão e colaboração de todos na proteção dos Direitos Autorais e
                        Direitos de Propriedade Intelectual.
                        <br />
                    </p>

                </div>

                <div>
                    <Advertising />
                </div>

            </main>
            <div>
                <DigitalWeekly />
                <DigitalBiWeekly/>
            </div>
        </>
    )
}