import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import styles from "./busca.module.scss";
import Share from "../../../components/Share";
import { Advertising } from "@/src/components/Advertising";
import SeeToo from "@/src/components/SeeToo";
import DigitalWeekly from "@/src/components/DigitalWeekly";
import DigitalBiWeekly from "@/src/components/digitalBiWeekly";

export default function News(){
    const { query } = useRouter();

    const [dados, setDados] = useState([]);
    const [load, setLoad] = useState(false);

    useEffect(() =>{   
            const colunistaNome = query?.colunista;
            fetch('/api/controller/buscarBancoUnico/',{
                method: 'POST',
                body: JSON.stringify({'busca': 'colunistaIndi', 'indicadorBusca': colunistaNome }), 
                headers:{
                    'Content-Type': 'application/json'
                }
            }).then(response => response.json()).then(data => {
                setDados(data.reverse());
                setLoad(true);
            });
    }, [query?.colunista]);
    
    if(load)
    return(
        <>
            <Head>
                <title> Colunas - JS </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <main>
                <div className="w-4/5 m-auto py-5">
                    <div className="flex items-center py-5">
                        <img src={`data:image;base64, ${Buffer.from(dados[0].imagem.data).toString('base64')}`} alt={`Foto de ${query?.colunista}`} className="px-4 w-1/12" />
                        <div>
                            <h1 className="pt-3 text-3xl font-light"> { query?.colunista }</h1>
                            <h2 className="pt-3 px-4 text-base"> {dados[0].descricao}</h2>
                        </div>
                    </div>
                    <div className="w-4/5 m-auto py-4">
                        {dados.map((dado, key)=>(
                            <div className="border-2 hover:scale-[98%] duration-300 p-2 px-4 rounded-xl">
                                <a href={`/columns/${dado.titulo}`} className="underline py-4 ">
                                    <h1 key={key} className=""> { (dado.titulo).substr(0,80) }... </h1>
                                    <h2 className=""> { (dado.texto).substr(0,100) }...</h2>
                                </a>
                            </div>
                        ))}
                    </div>
                </div>
                <SeeToo/>
                <DigitalWeekly/>
                <DigitalBiWeekly/>
            </main>
        </>
    );
}