import Head from "next/head";
import Contact from "../components/emailJS";
import DigitalWeekly from "../components/DigitalWeekly";
import DigitalBiWeekly from "../components/digitalBiWeekly";
import CanalJs from "../components/PreviewListYoutube";
import NewspaperThreeColumns from "../components/NewspaperThreeColumns";
import SeeToo from "../components/SeeToo";
import styles from "../styles/Home.module.scss"
import { Advertising } from "../components/Advertising";
import LastNewsHome from "../components/componentePagInicial";

export default function teste() {
  return (
    <>
      <Head>
        <title>Jornal do Sudoeste</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      
        <main className="flex flex-col p-4 overflow-x-hidden">
          <section className="my-8">
            <LastNewsHome />

          </section>
          

          <section className="my-4">
            <CanalJs/>
          </section>

          <section className="my-4">
            <NewspaperThreeColumns />
          </section>

          <Advertising />
          <DigitalWeekly/>
          <DigitalBiWeekly/>
          <Contact />
        </main>



    </>
  );

}
