import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import styles from "../news/news.module.scss";
import Share from "../../components/Share";
import Comments from "../../components/comments";
import { Advertising } from "@/src/components/Advertising";
import SeeToo from "@/src/components/SeeToo";
import DigitalWeekly from "@/src/components/DigitalWeekly";
import ComponentePagInicial from "@/src/components/componentePagInicial";
import DigitalBiWeekly from "@/src/components/digitalBiWeekly";

export default function News(){
    const { query } = useRouter();

    const [dados, setDados] = useState([]);
    const [load, setLoad] = useState(false);
    
    useEffect(() =>{   
            const noticiaTitulo = query?.noticias;
            fetch('/api/controller/buscarBancoUnico/',{
                method: 'POST',
                body: JSON.stringify({'busca': 'noticias', 'indicadorBusca': noticiaTitulo }), 
                headers:{
                    'Content-Type': 'application/json'
                }
            }).then(response => response.json()).then(data => {
                setDados(data);
                setLoad(true);
            });
    }, [query?.noticias]);

    
    
    
    if(load){
        return(
            <>
                <Head>
                    <title> { dados.titulo } - JS </title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.png" />
                </Head>


                <main>
                    <div className={styles.headerNoticiasIndi}>
                        <h1> { dados.titulo }</h1>
                        <h2> { dados.subtitulo }</h2>
                        <h4> Por { dados.autor }</h4>
                        <h4>Publicado em { dados.data }</h4> 
                        <img src={`data:image;base64, ${Buffer.from(dados.imagem.data).toString('base64')}`} alt="" className="object-cover" />
                        <span 
                            className="flex items-center justify-end"
                        > 
                            Foto de {dados.autor_imagem}
                        </span>
                    </div>
                    <div className={styles.conteudoNoticiasIndi}>
                        <Share/>
                        <p className="text-justify"> 
                            { dados.texto }
                        </p>
                        <h5></h5>
                    </div>
                    <Comments id={dados.id}/>
                    <SeeToo/>
                    <DigitalWeekly/>
                    <DigitalBiWeekly/>
                </main>
            </>
        );
    }
    else{
        return(
            <>
                <Head>
                        <title>Jornal Sudoeste </title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <link rel="icon" href="/favicon.png" />
                </Head>
            </>
        );
    }
}