import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "./news.module.scss";
import { Advertising } from "@/src/components/Advertising";
import DigitalWeekly from "@/src/components/DigitalWeekly";
import DigitalBiWeekly from "@/src/components/digitalBiWeekly";

export default function News() {
    const [dados, setDados] = useState([]);
    const [load, setLoad] = useState(false);

    useEffect(() => {
    fetch('api/controller/buscarBanco/', {
        method: 'POST',
        body: JSON.stringify({ 'busca': 'noticias' }),
        headers: {
            'Content-Type': 'application/json'
        }
    })
    .then(response => response.json())
    .then(data => {
        if(Array.isArray(data)) {
            setDados(data.reverse());
            setLoad(true);
        } else {
            console.error("Os dados retornados não são um array:", data);
        }
    })
    .catch(error => {
        console.error("Erro ao buscar os dados:", error);
    });
}, []);

    if (load)
        return (
            <>
                <Head>
                    <title> Notícias - JS</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.png" />
                </Head>
                <main>
                    <div className="flex flex-col text-center p-8">
                        <h1 className="font-light text-2xl uppercase"> Notícias </h1>
                        {/* <h2 className="font-light text-xl pt-4"> Acompanhe nossas repotagens! </h2> */}
                    </div>
                    <div className={styles.mainPageNoticias}>
                        {dados.map((noticia, key) => (
                            key < 1 ?
                                (
                                    <div className={styles.noticiasCardMaior} key={key}>
                                        <a href={`/news/${noticia.titulo}`}>
                                            <div className={styles.cardDentro}>
                                                <img src={`data:image;base64, ${Buffer.from(noticia.imagem.data).toString('base64')}`} className="object-cover" alt="" />
                                                <h3>{noticia.titulo}</h3>
                                            </div>
                                        </a>
                                    </div>
                                )
                                : (
                                    <div className={styles.noticiasCardMenor}>
                                        <a href={`/news/${noticia.titulo}`}>
                                            <div className={styles.cardDentro}>
                                                <img src={`data:image;base64, ${Buffer.from(noticia.imagem.data).toString('base64')}`} className="object-cover" alt="" />
                                                <h3>{noticia.titulo}</h3>
                                            </div>
                                        </a>
                                    </div>
                                )
                        ))}

                    </div>
                    <Advertising />
                    <DigitalWeekly />
                    <DigitalBiWeekly/>
                </main>
            </>
        );
    else {
        return (
            <Head>
                <title> Notícias - JS </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>
        );
    }
}