import Head from "next/head";
import styles from "./youtube.module.scss";
import { useEffect, useState } from "react";
import { Advertising } from "@/src/components/Advertising";
import SeeToo from "@/src/components/SeeToo";
import DigitalWeekly from "@/src/components/DigitalWeekly";
import DigitalBiWeekly from "@/src/components/digitalBiWeekly";

export default function YoutubeChannel() {

    const [dados, setDados] = useState([]);

    useEffect(() => {
        fetch(`https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=UC0S7RZd3vrOe88Zw9-x63BQ&maxResults=4&order=date&type=video&key=${process.env.NEXT_PUBLIC_YOUTUBE_CHANNEL_KEY}`).then(response => response.json()).then(data => setDados(data.items));
    }, []);

    return (
        <>
            <Head>
                <title>Canal JS - JS</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>

            {/* <main className="w-full flex flex-col items-center justify-center"> */}

            <main className="">
                <div className="w-4/5 m-auto">
                <div className="flex flex-col text-center p-8">
                    <h1 className="font-light text-2xl uppercase"> Canal JS</h1>
                </div>

                {/* <div className=" "> */}
                {dados.map((video, key) => (
                    key < 1 ?
                        <div className="grid grid-cols-2 justify-center gap-2">
                            <div className="max-w-md flex bg-white border border-gray-200 rounded-lg shadow">
                                <a href={`https://www.youtube.com/watch?v=${video.id.videoId}`} target="_blank">
                                    <img src={video.snippet.thumbnails.high.url}
                                        className="lg:object-cover lg:w-full md:h-96 lg:h-auto lg:rounded-none lg:rounded-s-lg "
                                    />
                                </a>
                            </div>
                            <div className="flex flex-col justify-between p-4 leading-normal">
                                <a href={`https://www.youtube.com/watch?v=${video.id.videoId}`} target="_blank">

                                    <h2 className="underline"> {video.snippet.title} </h2>
                                </a>
                                <p> O Jornal do Sudoeste está cada vez mais empenhado em oferecer um conteúdo diverso e de qualidade e em se aproximar de você por meio das plataformas digitais. Não deixe de continuar acompanhando nossas publicações e de nos seguir nas redes sociais para não perder nenhuma novidade:</p>
                                <p>Instagram: @jornaldosudoeste</p>
                                <p>Twitter: @jsudoestebahia</p>
                                <p>Facebook: Jornal do Sudoeste</p>
                            </div>
                        </div>
                        :
                        <></>
                ))}

                <div className="flex lg:flex-row flex-col gap-5 my-4">
                    {dados.map((video, key) => (
                        key > 0 && key < 4 ?
                            <div className="w-1/3 bg-white border border-gray-200 rounded-lg shadow bg-green-100 dark:border-gray-700">
                                <a
                                    href={`https://www.youtube.com/watch?v=${video.id.videoId}`}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    <img
                                        src={video.snippet.thumbnails.medium.url}
                                        className="lg:object-cover lg:rounded-t-lg w-full "
                                    />
                                    <div className="flex flex-col justify-between p-4 leading-normal">
                                        <h3 className="mb-1 lg:text-xl font-bold tracking-tight text-white-100 dark:text-white">
                                            {video.snippet.title}
                                        </h3>
                                    </div>

                                </a>
                            </div>
                            :
                            <></>
                    ))}

                </div>
                </div>
                <Advertising />
                <SeeToo/>
                <DigitalWeekly/>
                <DigitalBiWeekly/>
            </main>
        </>
    )
}