import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "./jornalDigital.module.scss";
import SeeToo from "@/src/components/SeeToo";
import { Advertising } from "@/src/components/Advertising";

export default function digitalWeekly(){
    const [dadosDiario, setDadosDiario] = useState([]);
    const [dadosSemanal, setDadosSemanal] = useState([]);
    const [dadosQuinzenal, setDadosQuinzenal] = useState([]);
    const [load, setLoad] = useState(false);
    
    
    useEffect(() =>{
            fetch('api/controller/buscarBanco/',{
                method: 'POST',
                body: JSON.stringify({'busca': 'edicoes_semanais'}), 
                headers:{
                    'Content-Type': 'application/json'
                }
            }).then(response => response.json()).then(data => {
                setDadosSemanal( data.reverse() );
                
            });
            fetch('api/controller/buscarBanco/',{
                method: 'POST',
                body: JSON.stringify({'busca': 'edicoes_diarias'}), 
                headers:{
                    'Content-Type': 'application/json'
                }
            }).then(response => response.json()).then(data => {
                setDadosDiario( data.reverse() );
                
            });
            fetch('api/controller/buscarBanco/',{
                method: 'POST',
                body: JSON.stringify({'busca': 'edicoes_quinzenais'}), 
                headers:{
                    'Content-Type': 'application/json'
                }
            }).then(response => response.json()).then(data => {
                setDadosQuinzenal( data.reverse() );
                setLoad(true);
            });
    }, []);
    
    if(load){
        addEventListener("copy", function(e){
            e.preventDefault();
            alert("A REPRODUÇÃO DO CONTEÚDO PUBLICADO NO PORTAL DO JORNAL DO SUDOESTE NÃO ESTÁ AUTORIZADA. PARA SOLICITAR AUTORIZAÇÃO, ENTRE EM CONTATO COM A REDAÇÃO: redacao@jornaldosudoeste.com");
        });
        return(
            <>
                <Head>
                    <title> Jornal Digital - JS</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.png" />
                </Head>
                <main>
                    <div className={styles.headerPageNoticias}>
                        <h1>Jornal Digital</h1>
                    </div>
                    <div className={styles.mainPageNoticias}>
                        <h2>Edições semanais: </h2>
                        <div className="w-full min-h-[300px] flex flex-wrap">
                        {   dadosSemanal.map((digital, key) => (
                                key < 9 ?
                                <div className={styles.noticiasCardMenor}>
                                    <a href={`/digitalWeekly/${digital.titulo}`}>
                                        <img src={`data:image;base64, ${Buffer.from(digital.imagem.data).toString('base64')}`} alt="" className=""/>
                                        <div className={styles.cardDentro}>
                                            <h3>{ digital.titulo }</h3>
                                        </div>
                                    </a>
                                </div>
                                :
                                null
                        ))}
                        </div>
                        <div className="w-full flex items-end justify-end">
                            <a href="/digitalWeekly/verTodos/edicoes_semanais" className="hover:underline text-xl"><h3>Ver Todas </h3></a>
                        </div>    

                        <h2>Edições Quinzenais: </h2>
                        <div className="w-full min-h-[300px] flex flex-wrap">
                        {   dadosQuinzenal.map((digital, key) => (
                                key < 6?
                                <div className={styles.noticiasCardMenor}>
                                    <a href={`/digitalWeekly/quinzenal/${digital.titulo}`}>
                                        <img src={`data:image;base64, ${Buffer.from(digital.imagem.data).toString('base64')}`} alt="" className=""/>
                                        <div className={styles.cardDentro}>
                                            <h3>{ digital.titulo }</h3>
                                        </div>
                                    </a>
                                </div>
                                :
                                null
                        ))}
                        </div>
                        <div className="w-full flex items-end justify-end">
                            <a href="/digitalWeekly/verTodos/edicoes_quinzenais" className="hover:underline text-xl"><h3>Ver Todas </h3></a>
                        </div>

                        <h2>Edições Diárias: </h2>
                            <div className="w-full min-h-[300px] flex flex-wrap">
                            {   dadosDiario.map((digital,key) =>(
                                key < 9 ?
                                <div className={styles.noticiasCardMenor}>
                                    <a href={`/digitalWeekly/diaria/${digital.titulo}`}>
                                        <img src={`data:image;base64, ${Buffer.from(digital.imagem.data).toString('base64')}`} alt="" className=""/>
                                        <div className={styles.cardDentro}>
                                            <h3>{ digital.titulo }</h3>
                                        </div>
                                    </a>
                                </div>
                                :
                                null
                            ))}
                        </div>
                        <div className="w-full flex items-end justify-end">
                            <a href="/digitalWeekly/verTodos/edicoes_diarias" className="hover:underline text-xl"><h3>Ver Todas </h3></a>
                        </div>

                    </div>
                    <Advertising/>
                    <SeeToo/>
                </main>
            </>
        );
    }
    else{
        return(
            <Head>
                    <title> Jornal do Sudoeste - JS </title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.png" />
            </Head>
        );
    }
}