import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Share from "@/src/components/Share";
import { Advertising } from "@/src/components/Advertising";
import SeeToo from "@/src/components/SeeToo";
import DigitalWeekly from "@/src/components/DigitalWeekly";

export default function Digital() {
    const { query } = useRouter();

    const [dados, setDados] = useState([]);
    const [load, setLoad] = useState(false);

    useEffect(() => {
        const digitalTitulo = query?.digital;
        fetch('/api/controller/buscarBancoUnico/', {
            method: 'POST',
            body: JSON.stringify({ 'busca': 'prefeiturasIndi', 'indicadorBusca': digitalTitulo }),
            headers: {
                'Content-Type': 'application/json'
            }
        }).then(response => response.json()).then(data => {
            setDados(data);
            setLoad(true);
        });
    }, [query?.digital]);



    if (load) {
        const pdfBase64 = Buffer.from(dados.pdf.data).toString('base64');
        const pdfUrl = `data:application/pdf;base64,${pdfBase64}`;
        return (
            <>
                <Head>
                    <title> {dados.titulo} - JS </title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.png" />
                </Head>
                <main>

                    <div className="m-auto py-20 w-full">
                        <embed src={`data:application/pdf;base64, ${Buffer.from(dados.pdf.data).toString('base64')}`} type="application/pdf" width="900" height="1000" className="m-auto" />
                    </div>

                    <div
                        className="flex items-center justify-center p-3 my-5 mx-44 font-bold text-white-100 rounded-full bg-green-100 border-green-300">
                        <a

                            href={pdfUrl}
                            download="document.pdf"
                        >
                            Não conseguiu ver o PDF? Faça o download do PDF aqui
                        </a>
                    </div>
                </main>
            </>
        );
    }
    else {
        return (
            <>
                <Head>
                    <title>Jornal Sudoeste </title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.png" />
                </Head>
            </>
        );
    }
}